/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author areznla
 */
public class TelaAddAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAddAluno
     */
    public TelaAddAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alunoTransferido = new javax.swing.ButtonGroup();
        telaMain = new javax.swing.JPanel();
        panelAction = new javax.swing.JPanel();
        alunos = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        panelFundo = new javax.swing.JPanel();
        alunoPrimario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoMae = new javax.swing.JTextField();
        campoPai = new javax.swing.JTextField();
        campoResp = new javax.swing.JTextField();
        campoNasc = new javax.swing.JFormattedTextField();
        campoCPF = new javax.swing.JFormattedTextField();
        campoMat = new javax.swing.JFormattedTextField();
        btnSubmit = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        alunoGinasio = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        campoNomeGin = new javax.swing.JTextField();
        campoMaeGin = new javax.swing.JTextField();
        campoPaiGin = new javax.swing.JTextField();
        campoRespGin = new javax.swing.JTextField();
        campoNascGin = new javax.swing.JFormattedTextField();
        campoCPFGin = new javax.swing.JFormattedTextField();
        campoMatGin = new javax.swing.JFormattedTextField();
        btnSubmitGin = new javax.swing.JButton();
        btnExitGin = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jRadioButtonGin = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        jRadioButtonGin2 = new javax.swing.JRadioButton();
        alunoEM = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        campoNomeEM = new javax.swing.JTextField();
        campoMaeEM = new javax.swing.JTextField();
        campoPaiEM = new javax.swing.JTextField();
        campoRespEM = new javax.swing.JTextField();
        campoNascEM = new javax.swing.JFormattedTextField();
        campoCPFEM = new javax.swing.JFormattedTextField();
        campoMatEM = new javax.swing.JFormattedTextField();
        btnSubmitEM = new javax.swing.JButton();
        btnExitEM = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jRadioButtonEM = new javax.swing.JRadioButton();
        jRadioButtonEM2 = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        alunoTecnico = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        campoNomeTec = new javax.swing.JTextField();
        campoMaeTec = new javax.swing.JTextField();
        campoPaiTec = new javax.swing.JTextField();
        campoRespTec = new javax.swing.JTextField();
        campoNascTec = new javax.swing.JFormattedTextField();
        campoCPFTec = new javax.swing.JFormattedTextField();
        campoMatTec = new javax.swing.JFormattedTextField();
        btnSubmitTec = new javax.swing.JButton();
        btnExitTec = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jRadioButtonTec = new javax.swing.JRadioButton();
        jLabel46 = new javax.swing.JLabel();
        jRadioButtonTec2 = new javax.swing.JRadioButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CADaster - Adicionar aluno");

        alunos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Primario [1-4 ano]", "Ginasio [5-9 ano]", "Ensino Medio [1-3 ano]", "Tecnico" }));
        alunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunosActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel17.setText("Tipo de aluno");

        javax.swing.GroupLayout panelActionLayout = new javax.swing.GroupLayout(panelAction);
        panelAction.setLayout(panelActionLayout);
        panelActionLayout.setHorizontalGroup(
            panelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(alunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelActionLayout.setVerticalGroup(
            panelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(alunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelFundo.setLayout(new java.awt.CardLayout());

        alunoPrimario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aluno Primário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel3.setText("Matricula *");

        jLabel8.setText("Responsável *");

        jLabel4.setText("Data de Nascimento *");

        jLabel7.setText("Nome Pai");

        jLabel6.setText("Nome Mãe");

        jLabel5.setText("CPF");

        jLabel2.setText("Nome *");

        try {
            campoNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoMat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnSubmit.setText("Confirmar Cadastro");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnExit.setText("Sair");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel18.setText("* Dados obrigatórios para realizar o cadastro");

        alunoTransferido.add(jRadioButton3);
        jRadioButton3.setText("Sim");

        jLabel28.setText("Aluno Transferido?");

        alunoTransferido.add(jRadioButton4);
        jRadioButton4.setText("Não");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alunoPrimarioLayout = new javax.swing.GroupLayout(alunoPrimario);
        alunoPrimario.setLayout(alunoPrimarioLayout);
        alunoPrimarioLayout.setHorizontalGroup(
            alunoPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunoPrimarioLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(alunoPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(alunoPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(campoNasc, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                    .addComponent(jLabel3)
                    .addComponent(campoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(alunoPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(campoMae, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPai, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(campoResp, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(alunoPrimarioLayout.createSequentialGroup()
                        .addComponent(jRadioButton3)
                        .addGap(61, 61, 61)
                        .addComponent(jRadioButton4))
                    .addComponent(jLabel28))
                .addGap(69, 69, 69))
            .addGroup(alunoPrimarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnSubmit)
                .addGap(37, 37, 37))
        );
        alunoPrimarioLayout.setVerticalGroup(
            alunoPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alunoPrimarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alunoPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alunoPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(alunoPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(alunoPrimarioLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(alunoPrimarioLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(alunoPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(alunoPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunoPrimarioLayout.createSequentialGroup()
                        .addGroup(alunoPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubmit)
                            .addComponent(btnExit))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunoPrimarioLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        panelFundo.add(alunoPrimario, "primario");

        alunoGinasio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aluno Ginásio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel29.setText("Matricula *");

        jLabel30.setText("Responsável *");

        jLabel31.setText("Data de Nascimento *");

        jLabel32.setText("Nome Pai");

        jLabel33.setText("Nome Mãe");

        jLabel34.setText("CPF");

        jLabel35.setText("Nome *");

        try {
            campoNascGin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoCPFGin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoMatGin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnSubmitGin.setText("Confirmar Cadastro");
        btnSubmitGin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitGinActionPerformed(evt);
            }
        });

        btnExitGin.setText("Sair");
        btnExitGin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitGinActionPerformed(evt);
            }
        });

        jLabel36.setText("* Dados obrigatórios para realizar o cadastro");

        alunoTransferido.add(jRadioButtonGin);
        jRadioButtonGin.setText("Sim");

        jLabel37.setText("Aluno Transferido?");

        alunoTransferido.add(jRadioButtonGin2);
        jRadioButtonGin2.setText("Não");
        jRadioButtonGin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGin2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alunoGinasioLayout = new javax.swing.GroupLayout(alunoGinasio);
        alunoGinasio.setLayout(alunoGinasioLayout);
        alunoGinasioLayout.setHorizontalGroup(
            alunoGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunoGinasioLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(alunoGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34)
                    .addComponent(jLabel31)
                    .addComponent(campoNomeGin, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(alunoGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(campoNascGin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoCPFGin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                    .addComponent(jLabel29)
                    .addComponent(campoMatGin, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(alunoGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(campoMaeGin, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPaiGin, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel30)
                    .addComponent(campoRespGin, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(alunoGinasioLayout.createSequentialGroup()
                        .addComponent(jRadioButtonGin)
                        .addGap(61, 61, 61)
                        .addComponent(jRadioButtonGin2))
                    .addComponent(jLabel37))
                .addGap(69, 69, 69))
            .addGroup(alunoGinasioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnExitGin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnSubmitGin)
                .addGap(37, 37, 37))
        );
        alunoGinasioLayout.setVerticalGroup(
            alunoGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alunoGinasioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alunoGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alunoGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoMaeGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNomeGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(alunoGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(alunoGinasioLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCPFGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMatGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNascGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(alunoGinasioLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPaiGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRespGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(alunoGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonGin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonGin2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(alunoGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunoGinasioLayout.createSequentialGroup()
                        .addGroup(alunoGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubmitGin)
                            .addComponent(btnExitGin))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunoGinasioLayout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        panelFundo.add(alunoGinasio, "ginasio");

        alunoEM.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aluno Ensino Médio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        alunoEM.setToolTipText("");

        jLabel19.setText("Matricula *");

        jLabel20.setText("Responsável *");

        jLabel21.setText("Data de Nascimento *");

        jLabel22.setText("Nome Pai");

        jLabel23.setText("Nome Mãe");

        jLabel24.setText("CPF *");

        jLabel25.setText("Nome *");

        try {
            campoNascEM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoCPFEM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoMatEM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnSubmitEM.setText("Confirmar Cadastro");
        btnSubmitEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitEMActionPerformed(evt);
            }
        });

        btnExitEM.setText("Sair");
        btnExitEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitEMActionPerformed(evt);
            }
        });

        jLabel26.setText("* Dados obrigatórios para realizar o cadastro");

        alunoTransferido.add(jRadioButtonEM);
        jRadioButtonEM.setText("Sim");

        alunoTransferido.add(jRadioButtonEM2);
        jRadioButtonEM2.setText("Não");
        jRadioButtonEM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEM2ActionPerformed(evt);
            }
        });

        jLabel27.setText("Aluno Transferido?");

        javax.swing.GroupLayout alunoEMLayout = new javax.swing.GroupLayout(alunoEM);
        alunoEM.setLayout(alunoEMLayout);
        alunoEMLayout.setHorizontalGroup(
            alunoEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunoEMLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(alunoEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jLabel21)
                    .addComponent(campoNomeEM, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(alunoEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(campoNascEM, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoCPFEM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                    .addComponent(jLabel19)
                    .addComponent(campoMatEM, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159)
                .addGroup(alunoEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(campoMaeEM, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPaiEM, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20)
                    .addComponent(campoRespEM, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(alunoEMLayout.createSequentialGroup()
                        .addComponent(jRadioButtonEM)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonEM2))
                    .addComponent(jLabel27))
                .addGap(65, 65, 65))
            .addGroup(alunoEMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExitEM, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnSubmitEM)
                .addGap(37, 37, 37))
        );
        alunoEMLayout.setVerticalGroup(
            alunoEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alunoEMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alunoEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alunoEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoMaeEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNomeEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(alunoEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alunoEMLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCPFEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMatEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(alunoEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(alunoEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNascEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonEM)
                            .addComponent(jRadioButtonEM2)))
                    .addGroup(alunoEMLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPaiEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRespEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(alunoEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunoEMLayout.createSequentialGroup()
                        .addGroup(alunoEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubmitEM)
                            .addComponent(btnExitEM))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunoEMLayout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        panelFundo.add(alunoEM, "EnsinoMedio");

        alunoTecnico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aluno Técnico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel38.setText("Matricula *");

        jLabel39.setText("Responsável *");

        jLabel40.setText("Data de Nascimento *");

        jLabel41.setText("Nome Pai");

        jLabel42.setText("Nome Mãe");

        jLabel43.setText("CPF *");

        jLabel44.setText("Nome *");

        campoPaiTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPaiTecActionPerformed(evt);
            }
        });

        try {
            campoNascTec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoCPFTec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoMatTec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnSubmitTec.setText("Confirmar Cadastro");
        btnSubmitTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitTecActionPerformed(evt);
            }
        });

        btnExitTec.setText("Sair");
        btnExitTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitTecActionPerformed(evt);
            }
        });

        jLabel45.setText("* Dados obrigatórios para realizar o cadastro");

        alunoTransferido.add(jRadioButtonTec);
        jRadioButtonTec.setText("Sim");

        jLabel46.setText("Aluno Transferido? *");

        alunoTransferido.add(jRadioButtonTec2);
        jRadioButtonTec2.setText("Não");
        jRadioButtonTec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTec2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alunoTecnicoLayout = new javax.swing.GroupLayout(alunoTecnico);
        alunoTecnico.setLayout(alunoTecnicoLayout);
        alunoTecnicoLayout.setHorizontalGroup(
            alunoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunoTecnicoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(alunoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(jLabel43)
                    .addComponent(jLabel40)
                    .addComponent(campoNomeTec, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(alunoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(campoNascTec, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoCPFTec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                    .addComponent(jLabel38)
                    .addComponent(campoMatTec, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(alunoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(campoMaeTec, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPaiTec, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel39)
                    .addComponent(campoRespTec, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(alunoTecnicoLayout.createSequentialGroup()
                        .addComponent(jRadioButtonTec)
                        .addGap(61, 61, 61)
                        .addComponent(jRadioButtonTec2))
                    .addComponent(jLabel46))
                .addGap(69, 69, 69))
            .addGroup(alunoTecnicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExitTec, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnSubmitTec)
                .addGap(37, 37, 37))
        );
        alunoTecnicoLayout.setVerticalGroup(
            alunoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alunoTecnicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alunoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alunoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoMaeTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNomeTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(alunoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(alunoTecnicoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCPFTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMatTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNascTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(alunoTecnicoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPaiTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRespTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(alunoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonTec, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonTec2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(alunoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunoTecnicoLayout.createSequentialGroup()
                        .addGroup(alunoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubmitTec)
                            .addComponent(btnExitTec))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunoTecnicoLayout.createSequentialGroup()
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        panelFundo.add(alunoTecnico, "tecnico");

        javax.swing.GroupLayout telaMainLayout = new javax.swing.GroupLayout(telaMain);
        telaMain.setLayout(telaMainLayout);
        telaMainLayout.setHorizontalGroup(
            telaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaMainLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(panelAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        telaMainLayout.setVerticalGroup(
            telaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaMainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(panelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitEMActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitEMActionPerformed

    private void jRadioButtonEM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEM2ActionPerformed
        
    }//GEN-LAST:event_jRadioButtonEM2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void btnExitGinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitGinActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitGinActionPerformed

    private void jRadioButtonGin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonGin2ActionPerformed

    private void btnExitTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitTecActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitTecActionPerformed

    private void jRadioButtonTec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTec2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTec2ActionPerformed

    private void alunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunosActionPerformed
        if(alunos.getSelectedItem().toString().equals("Primario [1-4 ano]")){
            CardLayout primario = (CardLayout) panelFundo.getLayout();
            primario.show(panelFundo,"primario");
        }else if(alunos.getSelectedItem().toString().equals("Ginasio [5-9 ano]")){
            CardLayout ginasio = (CardLayout) panelFundo.getLayout();
            ginasio.show(panelFundo, "ginasio");
        }else if(alunos.getSelectedItem().toString().equals("Ensino Medio [1-3 ano]")){
            CardLayout ensinoMedio = (CardLayout) panelFundo.getLayout();
            ensinoMedio.show(panelFundo, "EnsinoMedio");
        }else if(alunos.getSelectedItem().toString().equals("Tecnico")){
            CardLayout tecnico = (CardLayout) panelFundo.getLayout();
            tecnico.show(panelFundo,"tecnico");
        }else{
            CardLayout primario = (CardLayout) panelFundo.getLayout();
            primario.show(panelFundo,"primario");
        }
    }//GEN-LAST:event_alunosActionPerformed

    private void btnSubmitTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitTecActionPerformed
        if(campoNomeTec.getText().isEmpty()||campoCPFTec.getText().isEmpty()||campoRespTec.getText().isEmpty()
                ||campoNascTec.getText().isEmpty()||!(jRadioButtonTec.isSelected()||jRadioButtonTec2.isSelected())){
            
            JOptionPane.showMessageDialog(null, "Um ou Mais dados obrigatórios para o cadastro"
                    + " estão em branco, por favor verifique os dados digitados e tente novamente");
            
        }
    }//GEN-LAST:event_btnSubmitTecActionPerformed

    private void campoPaiTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPaiTecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPaiTecActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(campoNome.getText().isEmpty()||campoCPF.getText().isEmpty()||campoResp.getText().isEmpty()
                ||campoNasc.getText().isEmpty()||!(jRadioButton3.isSelected()||jRadioButton4.isSelected())){
            
            JOptionPane.showMessageDialog(null, "Um ou Mais dados obrigatórios para o cadastro"
                    + " estão em branco, por favor verifique os dados digitados e tente novamente");
            
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSubmitGinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitGinActionPerformed
        if(campoNomeGin.getText().isEmpty()||campoCPFGin.getText().isEmpty()||campoRespGin.getText().isEmpty()
                ||campoNascGin.getText().isEmpty()||!(jRadioButtonGin.isSelected()||jRadioButtonGin2.isSelected())){
            
            JOptionPane.showMessageDialog(null, "Um ou Mais dados obrigatórios para o cadastro"
                    + " estão em branco, por favor verifique os dados digitados e tente novamente");
            
        }
    }//GEN-LAST:event_btnSubmitGinActionPerformed

    private void btnSubmitEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitEMActionPerformed
        if(campoNomeEM.getText().isEmpty()||campoCPFEM.getText().isEmpty()||campoRespEM.getText().isEmpty()
                ||campoNascEM.getText().isEmpty()||!(jRadioButtonEM.isSelected()||jRadioButtonEM2.isSelected())){
            
            JOptionPane.showMessageDialog(null, "Um ou Mais dados obrigatórios para o cadastro"
                    + " estão em branco, por favor verifique os dados digitados e tente novamente");
            
        }
    }//GEN-LAST:event_btnSubmitEMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alunoEM;
    private javax.swing.JPanel alunoGinasio;
    private javax.swing.JPanel alunoPrimario;
    private javax.swing.JPanel alunoTecnico;
    private javax.swing.ButtonGroup alunoTransferido;
    private javax.swing.JComboBox<String> alunos;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExitEM;
    private javax.swing.JButton btnExitGin;
    private javax.swing.JButton btnExitTec;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmitEM;
    private javax.swing.JButton btnSubmitGin;
    private javax.swing.JButton btnSubmitTec;
    private javax.swing.JFormattedTextField campoCPF;
    private javax.swing.JFormattedTextField campoCPFEM;
    private javax.swing.JFormattedTextField campoCPFGin;
    private javax.swing.JFormattedTextField campoCPFTec;
    private javax.swing.JTextField campoMae;
    private javax.swing.JTextField campoMaeEM;
    private javax.swing.JTextField campoMaeGin;
    private javax.swing.JTextField campoMaeTec;
    private javax.swing.JFormattedTextField campoMat;
    private javax.swing.JFormattedTextField campoMatEM;
    private javax.swing.JFormattedTextField campoMatGin;
    private javax.swing.JFormattedTextField campoMatTec;
    private javax.swing.JFormattedTextField campoNasc;
    private javax.swing.JFormattedTextField campoNascEM;
    private javax.swing.JFormattedTextField campoNascGin;
    private javax.swing.JFormattedTextField campoNascTec;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeEM;
    private javax.swing.JTextField campoNomeGin;
    private javax.swing.JTextField campoNomeTec;
    private javax.swing.JTextField campoPai;
    private javax.swing.JTextField campoPaiEM;
    private javax.swing.JTextField campoPaiGin;
    private javax.swing.JTextField campoPaiTec;
    private javax.swing.JTextField campoResp;
    private javax.swing.JTextField campoRespEM;
    private javax.swing.JTextField campoRespGin;
    private javax.swing.JTextField campoRespTec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButtonEM;
    private javax.swing.JRadioButton jRadioButtonEM2;
    private javax.swing.JRadioButton jRadioButtonGin;
    private javax.swing.JRadioButton jRadioButtonGin2;
    private javax.swing.JRadioButton jRadioButtonTec;
    private javax.swing.JRadioButton jRadioButtonTec2;
    private javax.swing.JPanel panelAction;
    private javax.swing.JPanel panelFundo;
    private javax.swing.JPanel telaMain;
    private javax.swing.JComboBox<String> tipoAluno;
    private javax.swing.JComboBox<String> tipoAluno1;
    private javax.swing.JComboBox<String> tipoAluno2;
    private javax.swing.JComboBox<String> tipoAluno3;
    private javax.swing.JComboBox<String> tipoAluno4;
    private javax.swing.JComboBox<String> tipoAluno5;
    private javax.swing.JComboBox<String> tipoAluno6;
    private javax.swing.JComboBox<String> tipoAluno7;
    private javax.swing.JComboBox<String> tipoAluno8;
    // End of variables declaration//GEN-END:variables
}
