package view;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import modelbean.StudentBean;
import modeldao.InsertDao;

/**
 *
 * @author allan
 */
public class TelaAddAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAddAluno
     */
    
    private static TelaAddAluno tela;
    /*variavel estatica para verificar se existe mais de um objeto do mesmo
    tipo aberto*/ 
    
    public static TelaAddAluno getAbrir(){
        if(tela==null){
            tela=new TelaAddAluno();
        }
        /*se a tela estiver null, ou seja, se nao estiver nada aberto. Abra uma!
        Senao matenha a mesma aberta  */
        return tela;
    }
    public TelaAddAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alunoTransferido = new javax.swing.ButtonGroup();
        fundo = new javax.swing.JPanel();
        panelAcao = new javax.swing.JPanel();
        tipoAluno = new javax.swing.JComboBox<>();
        lblTIpoaluno = new javax.swing.JLabel();
        panelFundo = new javax.swing.JPanel();
        panelGinasio = new javax.swing.JPanel();
        lblMatriculaGin = new javax.swing.JLabel();
        lblRespGin = new javax.swing.JLabel();
        lblNascGin = new javax.swing.JLabel();
        lblNomepaiGin = new javax.swing.JLabel();
        lblNomemaeGin = new javax.swing.JLabel();
        lblCPFGin = new javax.swing.JLabel();
        lblNomeGin = new javax.swing.JLabel();
        campoNomeGin = new javax.swing.JTextField();
        campoMaeGin = new javax.swing.JTextField();
        campoPaiGin = new javax.swing.JTextField();
        campoRespGin = new javax.swing.JTextField();
        campoNascGin = new javax.swing.JFormattedTextField();
        campoCPFGin = new javax.swing.JFormattedTextField();
        campoMatGin = new javax.swing.JFormattedTextField();
        lblInfoGin = new javax.swing.JLabel();
        rBtnsimGin = new javax.swing.JRadioButton();
        lblAlunoTrasfGin = new javax.swing.JLabel();
        lblCEPGin = new javax.swing.JLabel();
        campoCEPGin = new javax.swing.JFormattedTextField();
        lblEnderecoGin = new javax.swing.JLabel();
        campoEnderecoGin = new javax.swing.JTextField();
        lblBairroGin = new javax.swing.JLabel();
        campoBairroGin = new javax.swing.JTextField();
        lblAnoGin = new javax.swing.JLabel();
        tipoAnoGin = new javax.swing.JComboBox<>();
        rBtnnaoGin = new javax.swing.JRadioButton();
        btnApagarGinasio = new javax.swing.JButton();
        btnCadastrarGinasio = new javax.swing.JButton();
        panelEM = new javax.swing.JPanel();
        lblMatriculaEM = new javax.swing.JLabel();
        lblRespEM = new javax.swing.JLabel();
        lblNascEM = new javax.swing.JLabel();
        lblNomepaiEM = new javax.swing.JLabel();
        lblNomemaeEM = new javax.swing.JLabel();
        lblCPFEM = new javax.swing.JLabel();
        lblNomeEM = new javax.swing.JLabel();
        campoNomeEM = new javax.swing.JTextField();
        campoMaeEM = new javax.swing.JTextField();
        campoPaiEM = new javax.swing.JTextField();
        campoRespEM = new javax.swing.JTextField();
        campoNascEM = new javax.swing.JFormattedTextField();
        campoCPFEM = new javax.swing.JFormattedTextField();
        campoMatEM = new javax.swing.JFormattedTextField();
        lblInfoEM = new javax.swing.JLabel();
        rBtnsimEM = new javax.swing.JRadioButton();
        rBtnnaoEM = new javax.swing.JRadioButton();
        lblAlunoTransfEM = new javax.swing.JLabel();
        lblCEPEM = new javax.swing.JLabel();
        campoCEPEM = new javax.swing.JFormattedTextField();
        lblEnderecoEM = new javax.swing.JLabel();
        campoEnderecoEM = new javax.swing.JTextField();
        lblBairroEM = new javax.swing.JLabel();
        campoBairroEM = new javax.swing.JTextField();
        lblAnoEM = new javax.swing.JLabel();
        anoEM = new javax.swing.JComboBox<>();
        panelTecnico = new javax.swing.JPanel();
        lblMatriculaTec = new javax.swing.JLabel();
        lblRespTec = new javax.swing.JLabel();
        lblNascTec = new javax.swing.JLabel();
        lblNomepaiTec = new javax.swing.JLabel();
        lblNomemaeTec = new javax.swing.JLabel();
        lblCPFTec = new javax.swing.JLabel();
        lblNomeTec = new javax.swing.JLabel();
        campoNomeTec = new javax.swing.JTextField();
        campoMaeTec = new javax.swing.JTextField();
        campoRespTec = new javax.swing.JTextField();
        campoNascTec = new javax.swing.JFormattedTextField();
        campoCPFTec = new javax.swing.JFormattedTextField();
        campoMatTec = new javax.swing.JFormattedTextField();
        lblInfoTec = new javax.swing.JLabel();
        rBtnsimTec = new javax.swing.JRadioButton();
        lblAlunotransfTec = new javax.swing.JLabel();
        lblCursoTec = new javax.swing.JLabel();
        tipoCursotecnico = new javax.swing.JComboBox<>();
        lblBolsaTec = new javax.swing.JLabel();
        lblPCentTec = new javax.swing.JLabel();
        tipoBolsaTec = new javax.swing.JComboBox<>();
        lblCEPTec = new javax.swing.JLabel();
        campoCEPTec = new javax.swing.JFormattedTextField();
        lblEnderecoTec = new javax.swing.JLabel();
        campoEnderecoTec = new javax.swing.JTextField();
        lblBairroTec = new javax.swing.JLabel();
        campoBairroTec = new javax.swing.JTextField();
        campoPaiTec = new javax.swing.JTextField();
        rBtnnaoTec = new javax.swing.JRadioButton();
        panelPrimario = new javax.swing.JPanel();
        lblMatricula = new javax.swing.JLabel();
        lblResp = new javax.swing.JLabel();
        lblNasc = new javax.swing.JLabel();
        lblNomepai = new javax.swing.JLabel();
        lblNomemae = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoMae = new javax.swing.JTextField();
        campoPai = new javax.swing.JTextField();
        campoResp = new javax.swing.JTextField();
        campoNasc = new javax.swing.JFormattedTextField();
        campoCPF = new javax.swing.JFormattedTextField();
        campoMat = new javax.swing.JFormattedTextField();
        lblInfo = new javax.swing.JLabel();
        lblCEP = new javax.swing.JLabel();
        campoCEP = new javax.swing.JFormattedTextField();
        lblEndereco = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        campoBairro = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        tipoAno = new javax.swing.JComboBox<>();
        btnCadastrarPrimario = new javax.swing.JButton();
        btnApagarPrimario = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("CADaster - Adicionar aluno");

        tipoAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Primario [1-4 ano]", "Ginasio [5-9 ano]", "Ensino Medio [1-3 ano]", "Tecnico" }));
        tipoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAlunoActionPerformed(evt);
            }
        });

        lblTIpoaluno.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblTIpoaluno.setText("Tipo de aluno");

        javax.swing.GroupLayout panelAcaoLayout = new javax.swing.GroupLayout(panelAcao);
        panelAcao.setLayout(panelAcaoLayout);
        panelAcaoLayout.setHorizontalGroup(
            panelAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTIpoaluno)
                    .addComponent(tipoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelAcaoLayout.setVerticalGroup(
            panelAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTIpoaluno)
                .addGap(18, 18, 18)
                .addComponent(tipoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelFundo.setLayout(new java.awt.CardLayout());

        panelGinasio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aluno Ginásio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        lblMatriculaGin.setText("Matricula *");

        lblRespGin.setText("Responsável *");

        lblNascGin.setText("Data de Nascimento *");

        lblNomepaiGin.setText("Nome Pai");

        lblNomemaeGin.setText("Nome Mãe");

        lblCPFGin.setText("CPF *");

        lblNomeGin.setText("Nome *");

        try {
            campoNascGin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoCPFGin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoMatGin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblInfoGin.setText("* Dados obrigatórios para realizar o cadastro");

        alunoTransferido.add(rBtnsimGin);
        rBtnsimGin.setText("Sim");

        lblAlunoTrasfGin.setText("Aluno Transferido? *");

        lblCEPGin.setText("CEP *");

        try {
            campoCEPGin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblEnderecoGin.setText("Endereco *");

        lblBairroGin.setText("Bairro");

        lblAnoGin.setText("Ano *");

        tipoAnoGin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "6", "7", "8", "9" }));

        alunoTransferido.add(rBtnnaoGin);
        rBtnnaoGin.setText("Não");

        btnApagarGinasio.setText("Apagar");
        btnApagarGinasio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarGinasioActionPerformed(evt);
            }
        });

        btnCadastrarGinasio.setText("Cadastrar");
        btnCadastrarGinasio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarGinasioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGinasioLayout = new javax.swing.GroupLayout(panelGinasio);
        panelGinasio.setLayout(panelGinasioLayout);
        panelGinasioLayout.setHorizontalGroup(
            panelGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGinasioLayout.createSequentialGroup()
                .addGap(49, 142, Short.MAX_VALUE)
                .addGroup(panelGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNomeGin)
                    .addComponent(lblCPFGin)
                    .addComponent(lblNascGin)
                    .addComponent(campoNascGin)
                    .addComponent(campoCPFGin, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(lblMatriculaGin)
                    .addComponent(campoMatGin, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(campoNomeGin))
                .addGap(130, 130, 130)
                .addGroup(panelGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomemaeGin)
                    .addComponent(campoMaeGin, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPaiGin, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomepaiGin)
                    .addComponent(lblRespGin)
                    .addComponent(campoRespGin, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelGinasioLayout.createSequentialGroup()
                        .addComponent(rBtnsimGin)
                        .addGap(34, 34, 34)
                        .addComponent(rBtnnaoGin))
                    .addComponent(lblAlunoTrasfGin))
                .addGap(130, 130, 130)
                .addGroup(panelGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGinasioLayout.createSequentialGroup()
                        .addComponent(lblAnoGin)
                        .addGap(18, 18, 18)
                        .addComponent(tipoAnoGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGinasioLayout.createSequentialGroup()
                            .addComponent(btnApagarGinasio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCadastrarGinasio))
                        .addComponent(lblCEPGin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblEnderecoGin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoEnderecoGin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblBairroGin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoBairroGin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoCEPGin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                .addGap(233, 233, 233))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGinasioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoGin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGinasioLayout.setVerticalGroup(
            panelGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGinasioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGinasioLayout.createSequentialGroup()
                        .addGroup(panelGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeGin)
                            .addComponent(lblNomemaeGin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoMaeGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNomeGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelGinasioLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblCPFGin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCPFGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMatriculaGin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoMatGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNascGin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNascGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelGinasioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblNomepaiGin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoPaiGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRespGin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoRespGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAlunoTrasfGin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rBtnsimGin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rBtnnaoGin)))))
                    .addGroup(panelGinasioLayout.createSequentialGroup()
                        .addComponent(lblCEPGin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCEPGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblEnderecoGin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoEnderecoGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBairroGin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBairroGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(panelGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoAnoGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnoGin))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(panelGinasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoGin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApagarGinasio)
                    .addComponent(btnCadastrarGinasio))
                .addContainerGap())
        );

        panelFundo.add(panelGinasio, "ginasio");

        panelEM.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aluno Ensino Médio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panelEM.setToolTipText("");

        lblMatriculaEM.setText("Matricula *");

        lblRespEM.setText("Responsável *");

        lblNascEM.setText("Data de Nascimento *");

        lblNomepaiEM.setText("Nome Pai");

        lblNomemaeEM.setText("Nome Mãe");

        lblCPFEM.setText("CPF *");

        lblNomeEM.setText("Nome *");

        try {
            campoNascEM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoCPFEM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoMatEM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblInfoEM.setText("* Dados obrigatórios para realizar o cadastro");

        alunoTransferido.add(rBtnsimEM);
        rBtnsimEM.setText("Sim");

        alunoTransferido.add(rBtnnaoEM);
        rBtnnaoEM.setText("Não");
        rBtnnaoEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnnaoEMActionPerformed(evt);
            }
        });

        lblAlunoTransfEM.setText("Aluno Transferido? *");

        lblCEPEM.setText("CEP *");

        try {
            campoCEPEM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblEnderecoEM.setText("Endereco *");

        lblBairroEM.setText("Bairro");

        lblAnoEM.setText("Ano *");

        anoEM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "1", "2", "3" }));

        javax.swing.GroupLayout panelEMLayout = new javax.swing.GroupLayout(panelEM);
        panelEM.setLayout(panelEMLayout);
        panelEMLayout.setHorizontalGroup(
            panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEMLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNascEM)
                            .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoNascEM)
                                .addComponent(lblNomeEM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCPFEM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoCPFEM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMatriculaEM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoMatEM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoNomeEM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(130, 130, 130)
                        .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoMaeEM, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPaiEM, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomepaiEM)
                            .addComponent(lblRespEM)
                            .addComponent(campoRespEM, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomemaeEM)
                            .addComponent(lblAlunoTransfEM)
                            .addGroup(panelEMLayout.createSequentialGroup()
                                .addComponent(rBtnsimEM)
                                .addGap(32, 32, 32)
                                .addComponent(rBtnnaoEM)))
                        .addGap(130, 130, 130)
                        .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCEPEM)
                            .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblEnderecoEM)
                                .addComponent(campoEnderecoEM)
                                .addComponent(lblBairroEM)
                                .addComponent(campoBairroEM)
                                .addComponent(campoCEPEM, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelEMLayout.createSequentialGroup()
                                .addComponent(lblAnoEM)
                                .addGap(18, 18, 18)
                                .addComponent(anoEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblInfoEM))
                .addGap(233, 233, 233))
        );
        panelEMLayout.setVerticalGroup(
            panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEM)
                    .addComponent(lblNomemaeEM)
                    .addComponent(lblCEPEM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomeEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMaeEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCEPEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEMLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCPFEM)
                            .addComponent(lblNomepaiEM))
                        .addGap(6, 6, 6)
                        .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoCPFEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPaiEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMatriculaEM)
                            .addComponent(lblRespEM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoMatEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoRespEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNascEM)
                            .addComponent(lblAlunoTransfEM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNascEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rBtnsimEM)
                            .addComponent(rBtnnaoEM)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEMLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEnderecoEM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoEnderecoEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBairroEM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBairroEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnoEM)
                            .addComponent(anoEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lblInfoEM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelFundo.add(panelEM, "EnsinoMedio");

        panelTecnico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aluno Técnico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        lblMatriculaTec.setText("Matricula *");

        lblRespTec.setText("Responsável *");

        lblNascTec.setText("Data de Nascimento *");

        lblNomepaiTec.setText("Nome Pai");

        lblNomemaeTec.setText("Nome Mãe");

        lblCPFTec.setText("CPF *");

        lblNomeTec.setText("Nome *");

        try {
            campoNascTec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoCPFTec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoMatTec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblInfoTec.setText("* Dados obrigatórios para realizar o cadastro");

        alunoTransferido.add(rBtnsimTec);
        rBtnsimTec.setText("Sim");

        lblAlunotransfTec.setText("Aluno Transferido? *");

        lblCursoTec.setText("Curso *");

        tipoCursotecnico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Redes", "Programacao", "A. Industrial", "Eng. Mecanica" }));

        lblBolsaTec.setText("Bolsa *");

        lblPCentTec.setText("%");

        tipoBolsaTec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "0", "30", "50", "70", "75", "90", "100" }));

        lblCEPTec.setText("CEP *");

        try {
            campoCEPTec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblEnderecoTec.setText("Endereco *");

        lblBairroTec.setText("Bairro");

        alunoTransferido.add(rBtnnaoTec);
        rBtnnaoTec.setText("Não");

        javax.swing.GroupLayout panelTecnicoLayout = new javax.swing.GroupLayout(panelTecnico);
        panelTecnico.setLayout(panelTecnicoLayout);
        panelTecnicoLayout.setHorizontalGroup(
            panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTecnicoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeTec)
                    .addComponent(lblCPFTec)
                    .addComponent(lblNascTec)
                    .addComponent(campoNomeTec, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(campoNascTec, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoCPFTec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                    .addComponent(lblMatriculaTec)
                    .addComponent(campoMatTec, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTecnicoLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomemaeTec)
                            .addComponent(campoMaeTec, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomepaiTec)
                            .addComponent(lblRespTec)
                            .addComponent(campoRespTec, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTecnicoLayout.createSequentialGroup()
                                .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAlunotransfTec)
                                    .addGroup(panelTecnicoLayout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(rBtnnaoTec)))
                                .addGap(77, 77, 77)
                                .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoBolsaTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBolsaTec)))
                            .addComponent(campoPaiTec, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTecnicoLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(rBtnsimTec)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPCentTec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblCEPTec)
                        .addComponent(lblEnderecoTec)
                        .addComponent(campoEnderecoTec)
                        .addComponent(lblBairroTec)
                        .addComponent(campoBairroTec)
                        .addComponent(campoCEPTec, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCursoTec)
                    .addComponent(tipoCursotecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
            .addGroup(panelTecnicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoTec)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTecnicoLayout.setVerticalGroup(
            panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTecnicoLayout.createSequentialGroup()
                .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTecnicoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeTec)
                            .addComponent(lblNomemaeTec))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoMaeTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNomeTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(lblNomepaiTec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPaiTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRespTec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRespTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTecnicoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCEPTec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCEPTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblEnderecoTec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoEnderecoTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBairroTec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBairroTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTecnicoLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblMatriculaTec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMatTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCPFTec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCPFTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTecnicoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblAlunotransfTec)
                        .addGap(18, 18, 18)
                        .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rBtnsimTec, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rBtnnaoTec))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelTecnicoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblCursoTec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoCursotecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTecnicoLayout.createSequentialGroup()
                        .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTecnicoLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblNascTec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNascTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTecnicoLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblBolsaTec)
                                .addGap(18, 18, 18)
                                .addGroup(panelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tipoBolsaTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPCentTec))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(lblInfoTec, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        panelFundo.add(panelTecnico, "tecnico");

        panelPrimario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aluno Primário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        lblMatricula.setText("Matricula *");

        lblResp.setText("Responsável *");

        lblNasc.setText("Data de Nascimento *");

        lblNomepai.setText("Nome Pai");

        lblNomemae.setText("Nome Mãe");

        lblCPF.setText("CPF *");

        lblNome.setText("Nome *");

        try {
            campoNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoMat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblInfo.setText("* Dados obrigatórios para realizar o cadastro");

        lblCEP.setText("CEP *");

        try {
            campoCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblEndereco.setText("Endereco *");

        lblBairro.setText("Bairro");

        lblAno.setText("Ano *");

        tipoAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "1", "2", "3", "4", "5" }));

        btnCadastrarPrimario.setText("Cadastrar");
        btnCadastrarPrimario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPrimarioActionPerformed(evt);
            }
        });

        btnApagarPrimario.setText("Apagar");
        btnApagarPrimario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarPrimarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrimarioLayout = new javax.swing.GroupLayout(panelPrimario);
        panelPrimario.setLayout(panelPrimarioLayout);
        panelPrimarioLayout.setHorizontalGroup(
            panelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrimarioLayout.createSequentialGroup()
                .addGroup(panelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrimarioLayout.createSequentialGroup()
                        .addGap(49, 142, Short.MAX_VALUE)
                        .addGroup(panelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNome)
                            .addComponent(lblCPF)
                            .addComponent(lblNasc)
                            .addComponent(campoNasc)
                            .addComponent(campoCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(lblMatricula)
                            .addComponent(campoMat, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(campoNome))
                        .addGap(130, 130, 130)
                        .addGroup(panelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomemae)
                            .addComponent(campoMae, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPai, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomepai)
                            .addComponent(lblResp)
                            .addComponent(campoResp, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130))
                    .addGroup(panelPrimarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrimarioLayout.createSequentialGroup()
                        .addComponent(lblAno)
                        .addGap(18, 18, 18)
                        .addComponent(tipoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelPrimarioLayout.createSequentialGroup()
                            .addComponent(btnApagarPrimario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCadastrarPrimario))
                        .addComponent(lblCEP, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblBairro, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoBairro, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoCEP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                .addGap(233, 233, 233))
        );
        panelPrimarioLayout.setVerticalGroup(
            panelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrimarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrimarioLayout.createSequentialGroup()
                        .addGroup(panelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(lblNomemae))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrimarioLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblCPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMatricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPrimarioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblNomepai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPrimarioLayout.createSequentialGroup()
                        .addComponent(lblCEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(panelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAno))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(panelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarPrimario)
                    .addComponent(btnApagarPrimario))
                .addContainerGap())
        );

        panelFundo.add(panelPrimario, "primario");

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(panelAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(panelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rBtnnaoEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnnaoEMActionPerformed
        
    }//GEN-LAST:event_rBtnnaoEMActionPerformed
    
    //limpa os jTextFild e afins do alunoPrimario
    private void limparInputs(){
            campoNome.setText("");
            campoMat.setText("");
            campoCPF.setText("");
            campoNasc.setText("");
            campoCEP.setText("");
            campoEndereco.setText("");
            campoBairro.setText("");
            campoMae.setText("");
            campoPai.setText("");
            campoResp.setText("");
            tipoAno.setSelectedItem("Selecione");
    }
    
    private void limparInputs(String ginasio){
            campoNomeGin.setText("");
            campoMatGin.setText("");
            campoCPFGin.setText("");
            campoNascGin.setText("");
            campoCEPGin.setText("");
            campoEnderecoGin.setText("");
            campoBairroGin.setText("");
            campoMaeGin.setText("");
            campoPaiGin.setText("");
            campoRespGin.setText("");
            tipoAnoGin.setSelectedItem("Selecione");
            if(rBtnnaoGin.isSelected()){
                alunoTransferido.clearSelection();
            }
            if(rBtnsimGin.isSelected()){
                alunoTransferido.clearSelection();
            }
    }
    //Trabalho com os panels atraves do cardLayout
    private void tipoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAlunoActionPerformed
        switch (tipoAluno.getSelectedItem().toString()) {
            case "Primario [1-4 ano]":
                {
                    CardLayout primario = (CardLayout) panelFundo.getLayout();
                    primario.show(panelFundo,"primario");
                    break;
                }
            case "Ginasio [5-9 ano]":
                CardLayout ginasio = (CardLayout) panelFundo.getLayout();
                ginasio.show(panelFundo, "ginasio");
                break;
            case "Ensino Medio [1-3 ano]":
                CardLayout ensinoMedio = (CardLayout) panelFundo.getLayout();
                ensinoMedio.show(panelFundo, "EnsinoMedio");
                break;
            case "Tecnico":
                CardLayout tecnico = (CardLayout) panelFundo.getLayout();
                tecnico.show(panelFundo,"tecnico");
                break;
            default:
                {
                    CardLayout primario = (CardLayout) panelFundo.getLayout();
                    primario.show(panelFundo,"primario");
                    break;
                }
        }
    }//GEN-LAST:event_tipoAlunoActionPerformed

    
    
    //Cadastrar aluno DO ENSINO PRIMARIO
    private void btnCadastrarPrimarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPrimarioActionPerformed
        if(campoNome.getText().equals("") || campoCPF.getText().equals("") || campoMat.getText().equals("")
            || campoNasc.getText().equals("") || campoResp.getText().equals("") || campoCEP.getText().equals("")
            || campoEndereco.getText().equals("") || tipoAno.getSelectedItem().toString().equals("Selecione")){
            JOptionPane.showMessageDialog(null, "Um ou mais campos obrigatórios estão em branco\n"
                + "ou não foram preenchidos corretamente");
        }else{
            int count=0;
            if(campoMae.getText().equals("")){
                count++;
            }
            if(campoPai.getText().equals("")){
                count+=2;
            }
            if(campoBairro.getText().equals("")){
                count+=4;
            }

            StudentBean student = new StudentBean();
            InsertDao insert = new InsertDao();
            student.setGrau("anoPrimario");
            student.setNome(campoNome.getText());
            student.setMatricula(campoMat.getText());
            student.setCPF(campoCPF.getText());
            student.setDataNasc(campoNasc.getText());
            student.setCEP(campoCEP.getText());
            student.setEndereco(campoEndereco.getText());
            student.setBairro(campoBairro.getText());
            student.setNomeMae(campoMae.getText());
            student.setNomePai(campoPai.getText());
            student.setResponsavel(campoResp.getText());
            student.setAno(tipoAno.getSelectedItem().toString());

            insert.criarAluno(student, count);
            limparInputs();
        }
    }//GEN-LAST:event_btnCadastrarPrimarioActionPerformed

    private void btnApagarPrimarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarPrimarioActionPerformed
        limparInputs();
    }//GEN-LAST:event_btnApagarPrimarioActionPerformed

    private void btnCadastrarGinasioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarGinasioActionPerformed
        if(campoNomeGin.getText().equals("") || campoCPFGin.getText().equals("") || campoMatGin.getText().equals("")
            || campoNascGin.getText().equals("") || campoRespGin.getText().equals("") || campoCEPGin.getText().equals("")
            || campoEnderecoGin.getText().equals("") || tipoAnoGin.getSelectedItem().toString().equals("Selecione")
            || (!rBtnnaoGin.isSelected() && !rBtnsimGin.isSelected())){
            JOptionPane.showMessageDialog(null, "Um ou mais campos obrigatórios estão em branco\n"
                + "ou não foram preenchidos corretamente");
        }else{
            int count=0;
            String transferido="";
            if(campoMaeGin.getText().equals("")){
                count++;
            }
            if(campoPaiGin.getText().equals("")){
                count+=2;
            }
            if(campoBairroGin.getText().equals("")){
                count+=4;
            }

            StudentBean student = new StudentBean();
            InsertDao insert = new InsertDao();
            student.setGrau("anoGinasio");
            student.setNome(campoNomeGin.getText());
            student.setMatricula(campoMatGin.getText());
            student.setCPF(campoCPFGin.getText());
            student.setDataNasc(campoNascGin.getText());
            student.setCEP(campoCEPGin.getText());
            student.setEndereco(campoEnderecoGin.getText());
            student.setBairro(campoBairroGin.getText());
            student.setNomeMae(campoMaeGin.getText());
            student.setNomePai(campoPaiGin.getText());
            student.setResponsavel(campoRespGin.getText());
            student.setAno(tipoAnoGin.getSelectedItem().toString());
            if(rBtnnaoGin.isSelected()){
                transferido="N";
            }
            if(rBtnsimGin.isSelected()){
                transferido="S";
            }
            insert.criarAluno(student, count,transferido);
            
        }    }//GEN-LAST:event_btnCadastrarGinasioActionPerformed

    private void btnApagarGinasioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarGinasioActionPerformed
        
        limparInputs("ginasio");
    }//GEN-LAST:event_btnApagarGinasioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup alunoTransferido;
    private javax.swing.JComboBox<String> anoEM;
    private javax.swing.JButton btnApagarGinasio;
    private javax.swing.JButton btnApagarPrimario;
    private javax.swing.JButton btnCadastrarGinasio;
    private javax.swing.JButton btnCadastrarPrimario;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoBairroEM;
    private javax.swing.JTextField campoBairroGin;
    private javax.swing.JTextField campoBairroTec;
    private javax.swing.JFormattedTextField campoCEP;
    private javax.swing.JFormattedTextField campoCEPEM;
    private javax.swing.JFormattedTextField campoCEPGin;
    private javax.swing.JFormattedTextField campoCEPTec;
    private javax.swing.JFormattedTextField campoCPF;
    private javax.swing.JFormattedTextField campoCPFEM;
    private javax.swing.JFormattedTextField campoCPFGin;
    private javax.swing.JFormattedTextField campoCPFTec;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoEnderecoEM;
    private javax.swing.JTextField campoEnderecoGin;
    private javax.swing.JTextField campoEnderecoTec;
    private javax.swing.JTextField campoMae;
    private javax.swing.JTextField campoMaeEM;
    private javax.swing.JTextField campoMaeGin;
    private javax.swing.JTextField campoMaeTec;
    private javax.swing.JFormattedTextField campoMat;
    private javax.swing.JFormattedTextField campoMatEM;
    private javax.swing.JFormattedTextField campoMatGin;
    private javax.swing.JFormattedTextField campoMatTec;
    private javax.swing.JFormattedTextField campoNasc;
    private javax.swing.JFormattedTextField campoNascEM;
    private javax.swing.JFormattedTextField campoNascGin;
    private javax.swing.JFormattedTextField campoNascTec;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeEM;
    private javax.swing.JTextField campoNomeGin;
    private javax.swing.JTextField campoNomeTec;
    private javax.swing.JTextField campoPai;
    private javax.swing.JTextField campoPaiEM;
    private javax.swing.JTextField campoPaiGin;
    private javax.swing.JTextField campoPaiTec;
    private javax.swing.JTextField campoResp;
    private javax.swing.JTextField campoRespEM;
    private javax.swing.JTextField campoRespGin;
    private javax.swing.JTextField campoRespTec;
    private javax.swing.JPanel fundo;
    private javax.swing.JLabel lblAlunoTransfEM;
    private javax.swing.JLabel lblAlunoTrasfGin;
    private javax.swing.JLabel lblAlunotransfTec;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblAnoEM;
    private javax.swing.JLabel lblAnoGin;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblBairroEM;
    private javax.swing.JLabel lblBairroGin;
    private javax.swing.JLabel lblBairroTec;
    private javax.swing.JLabel lblBolsaTec;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCEPEM;
    private javax.swing.JLabel lblCEPGin;
    private javax.swing.JLabel lblCEPTec;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPFEM;
    private javax.swing.JLabel lblCPFGin;
    private javax.swing.JLabel lblCPFTec;
    private javax.swing.JLabel lblCursoTec;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEnderecoEM;
    private javax.swing.JLabel lblEnderecoGin;
    private javax.swing.JLabel lblEnderecoTec;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInfoEM;
    private javax.swing.JLabel lblInfoGin;
    private javax.swing.JLabel lblInfoTec;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblMatriculaEM;
    private javax.swing.JLabel lblMatriculaGin;
    private javax.swing.JLabel lblMatriculaTec;
    private javax.swing.JLabel lblNasc;
    private javax.swing.JLabel lblNascEM;
    private javax.swing.JLabel lblNascGin;
    private javax.swing.JLabel lblNascTec;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeEM;
    private javax.swing.JLabel lblNomeGin;
    private javax.swing.JLabel lblNomeTec;
    private javax.swing.JLabel lblNomemae;
    private javax.swing.JLabel lblNomemaeEM;
    private javax.swing.JLabel lblNomemaeGin;
    private javax.swing.JLabel lblNomemaeTec;
    private javax.swing.JLabel lblNomepai;
    private javax.swing.JLabel lblNomepaiEM;
    private javax.swing.JLabel lblNomepaiGin;
    private javax.swing.JLabel lblNomepaiTec;
    private javax.swing.JLabel lblPCentTec;
    private javax.swing.JLabel lblResp;
    private javax.swing.JLabel lblRespEM;
    private javax.swing.JLabel lblRespGin;
    private javax.swing.JLabel lblRespTec;
    private javax.swing.JLabel lblTIpoaluno;
    private javax.swing.JPanel panelAcao;
    private javax.swing.JPanel panelEM;
    private javax.swing.JPanel panelFundo;
    private javax.swing.JPanel panelGinasio;
    private javax.swing.JPanel panelPrimario;
    private javax.swing.JPanel panelTecnico;
    private javax.swing.JRadioButton rBtnnaoEM;
    private javax.swing.JRadioButton rBtnnaoGin;
    private javax.swing.JRadioButton rBtnnaoTec;
    private javax.swing.JRadioButton rBtnsimEM;
    private javax.swing.JRadioButton rBtnsimGin;
    private javax.swing.JRadioButton rBtnsimTec;
    private javax.swing.JComboBox<String> tipoAluno;
    private javax.swing.JComboBox<String> tipoAno;
    private javax.swing.JComboBox<String> tipoAnoGin;
    private javax.swing.JComboBox<String> tipoBolsaTec;
    private javax.swing.JComboBox<String> tipoCursotecnico;
    // End of variables declaration//GEN-END:variables
}
